const days=[
['30 июля · четверг','Москва → Пекин','Вылет из Москвы в Пекин. В пути 7 часов 35 минут.','Паспорт · пауэрбанк','✈ В пути'],
['31 июля · пятница','Пекин → Инкоу','07:25 — прибытие в Пекин, завтрак, выезд на скоростном поезде в Инкоу. Время в пути ориентировочно 4 часа. Прибытие в Инкоу, размещение в двухместном номере в отеле на курорте. Ужин в ресторане отеля. Сбор группы — круг знакомства. Мягкая практика для восстановления после перелёта. Отдых.','Паспорт · вода · кофта','Инкоу · прогноз'],
['1 августа · суббота','Знакомство с резортом','Утренние и вечерние практики йоги, сонастройка с пространством. Осмотр территории резорта, завтрак, отдых на термальных источниках. Адаптация. Обед в ресторане отеля. Свободное время. Вечерняя практика йоги. Торжественное открытие смены в языковом лагере, концерт.','Купальник · сандалии · полотенце','Инкоу · прогноз'],
['2 августа · воскресенье','Стеклянный мост и храм','Завтрак, практика йоги уровня Земли. Выезд из отеля на экскурсию: Стеклянный мост, парк Бэйхай, буддийский храм. Возвращение в отель. Длительность 4,5–5 часов. Беседа-лекция о Благородных Истинах и буддизме. Вечерняя дыхательная практика, медитация.','Кроссовки · дождевик · SPF','Инкоу · прогноз'],
['3 августа · понедельник','Клиника и Инкоу','Завтрак, практики йоги. Выезд в клинику: диагностика в клинике традиционной китайской медицины, процедуры, прогулка по Инкоу, свободное время. Вечерняя дыхательная практика. Йога-нидра «Перепросмотр».','Медицинские документы · список лекарств','Инкоу · прогноз'],
['4 августа · вторник','Клиника и термы','Завтрак, практика йоги уровня Воды. Выезд в клинику, процедуры в клинике традиционной китайской медицины, отдых на термальных источниках. Свободное время. Вечерняя дыхательная практика; даосская медитация «Внутренняя улыбка».','Купальник · вода · полотенце','Инкоу · прогноз'],
['5 августа · среда','Далянь','Даосская практика уровня Воды. Завтрак. Экскурсия в Далянь. Отправление на скоростном поезде: Китайская Венеция, Парк труда, шопинг, прогулка, свободное время. Длительность 5 часов. Вечерняя даосская практика.','Паспорт · удобная обувь · веер','Далянь · прогноз'],
['6 августа · четверг','Практики и Инкоу','Завтрак, практики йоги уровня Воздуха. Процедуры в клинике традиционной китайской медицины, отдых на термальных источниках. Свободное время. Прогулка по Инкоу. Вечерний дыхательный семинар-практика «Энергия дыхания — Дыхательная аптечка».','Купальник · гермопакет','Инкоу · прогноз'],
['7 августа · пятница','Йога и восстановление','Завтрак, практики йоги, процедуры в клинике традиционной китайской медицины, отдых на термальных источниках. Свободное время. Вечерняя практика йога-нидры.','Купальник · полотенце','Инкоу · прогноз'],
['8 августа · суббота','Уровень Эфира','Завтрак, практики йоги уровня Эфира. Процедуры в клинике традиционной китайской медицины, отдых на термальных источниках. Вечерняя даосская медитация «Внутренняя улыбка».','Купальник · вода','Инкоу · прогноз'],
['9 августа · воскресенье','Инкоу → Пекин','Завтрак, выезд на скоростном поезде в Пекин, размещение в двухместном номере в отеле, ужин. Вечерняя практика интеграции новых опытов.','Паспорт · кофта в поезд','Пекин · прогноз'],
['10 августа · понедельник','Центр Пекина','Завтрак. Утренняя практика йоги Пяти Стихий. Выезд на обзорную экскурсию по Пекину: площадь Тяньаньмэнь и прогулка по пешеходной улице Ванфуцзин, шопинг. Свободное время.','Паспорт · SPF · вода','Пекин · прогноз'],
['11 августа · вторник','Великая Китайская стена','Утренняя практика пранаямы в парке, завтрак. Экскурсия: Великая Китайская стена, чайная церемония. Гала-ужин — утка по-пекински. Обмен впечатлениями и интеграция опыта от путешествия.','Кроссовки · дождевик · вентилятор','Пекин · прогноз'],
['12 августа · среда','Запретный город','Завтрак, утренняя практика йоги. Экскурсия: Запретный город, шопинг на Шёлковом рынке. Прогулка по центру. Свободное время. Вечерняя практика — йога-нидра «Создание Самкальпы».','Паспорт · веер · сумка для покупок','Пекин · прогноз'],
['13 августа · четверг','Пекин → Москва','Завтрак, завершение тура. 13:25 — вылет в Москву рейсом CZ341. 16:50 — прибытие в Москву.','Паспорт · проверить багаж','✈ В пути']
];
const images=['1508804185872-d7badad00f7d','1507525428034-b723cf961d3e','1547981609-4b6bfe67ca0b','1500530855697-b586d89ba3ee'];
const carousel=document.querySelector('#dayCarousel'); let day=0;
carousel.innerHTML='<div class="day-track">'+days.map((d,i)=>`<article class="day-card"><header class="day-card-head"><div><span class="date-line">${d[0]}</span><h3>${d[1]}</h3><b>День ${String(i+1).padStart(2,'0')}</b></div><div class="day-image" style="background-image:url(https://images.unsplash.com/photo-${images[i%images.length]}?auto=format&fit=crop&w=900&q=80)"></div></header><div class="day-columns"><section class="program"><h4>План дня</h4><p>${d[2]}</p></section><aside class="day-aside"><div class="take"><h4>Взять с собой</h4>${d[3].split(' · ').map(x=>'<span><i>✓</i>'+x+'</span>').join('')}</div><div class="tip"><i>💡</i><p><b>Совет</b> Проверьте вещи и прогноз перед выходом.</p></div></aside></div></article>`).join('')+'</div>';
let track=carousel.firstElementChild,detailed=[];const dots=document.querySelector('#dayDots');dots.innerHTML=days.map((_,i)=>`<i>${i+1}</i>`).join('');
const weatherPlaces=[
 {name:'Москва',date:'2026-07-30',lat:55.7558,lon:37.6173,tz:'Europe/Moscow'},{name:'Баюйцюань / Инкоу',date:'2026-07-31',lat:40.27,lon:122.12,tz:'Asia/Shanghai'},{name:'Баюйцюань / Инкоу',date:'2026-08-01',lat:40.27,lon:122.12,tz:'Asia/Shanghai'},{name:'Туаньшань / Бэйхай',date:'2026-08-02',lat:40.34,lon:122.23,tz:'Asia/Shanghai'},{name:'Баюйцюань / Инкоу',date:'2026-08-03',lat:40.27,lon:122.12,tz:'Asia/Shanghai'},{name:'Баюйцюань / Инкоу',date:'2026-08-04',lat:40.27,lon:122.12,tz:'Asia/Shanghai'},{name:'Далянь',date:'2026-08-05',lat:38.914,lon:121.6147,tz:'Asia/Shanghai'},{name:'Баюйцюань / Инкоу',date:'2026-08-06',lat:40.27,lon:122.12,tz:'Asia/Shanghai'},{name:'Баюйцюань / Инкоу',date:'2026-08-07',lat:40.27,lon:122.12,tz:'Asia/Shanghai'},{name:'Баюйцюань / Инкоу',date:'2026-08-08',lat:40.27,lon:122.12,tz:'Asia/Shanghai'},{name:'Пекин',date:'2026-08-09',lat:39.9042,lon:116.4074,tz:'Asia/Shanghai'},{name:'Пекин',date:'2026-08-10',lat:39.9042,lon:116.4074,tz:'Asia/Shanghai'},{name:'Великая Китайская стена / Пекин',date:'2026-08-11',lat:40.4319,lon:116.5704,tz:'Asia/Shanghai'},{name:'Пекин',date:'2026-08-12',lat:39.9042,lon:116.4074,tz:'Asia/Shanghai'},{name:'Пекин',date:'2026-08-13',lat:39.9042,lon:116.4074,tz:'Asia/Shanghai'}];
const weatherCache={};function syncCarouselHeight(){requestAnimationFrame(()=>{const card=track.children[day];if(card)carousel.style.height=card.offsetHeight+'px'})}function showDay(n){day=(n+days.length)%days.length;track.style.transform=`translateX(-${day*100}%)`;document.querySelector('#currentDayNumber').textContent=day+1;document.querySelector('#dayProgress').style.width=`${(day+1)/days.length*100}%`;dots.querySelectorAll('i').forEach((x,i)=>{x.className=i<day?'done':i===day?'active':'';x.textContent=i<day?'✓':i+1});const note=document.querySelector('#dayWeatherText');if(note&&detailed[day])note.innerHTML=detailed[day].weather;setWeatherPlace();loadWeather(false);syncCarouselHeight()}
document.querySelector('#prevDay').onclick=()=>showDay(day-1);document.querySelector('#nextDay').onclick=()=>showDay(day+1);document.querySelector('#nextTop').onclick=()=>showDay(day+1);let sx=0;carousel.ontouchstart=e=>sx=e.touches[0].clientX;carousel.ontouchend=e=>{const x=e.changedTouches[0].clientX-sx;if(Math.abs(x)>45)showDay(day+(x<0?1:-1))};showDay(0);
const forecast=[['08:00','🌧️','25°','20%'],['11:00','🌤️','27°','30%'],['14:00','🌧️','29°','45%'],['17:00','🌧️','28°','55%'],['20:00','🌙','26°','35%']];
document.querySelector('#forecastList').innerHTML=forecast.map(x=>`<div class="forecast-day"><span>${x[0]}</span><i>${x[1]}</i><b>${x[2]}</b><small>💧 ${x[3]}</small></div>`).join('');
document.querySelector('.forecast-list.mirror').innerHTML=document.querySelector('#forecastList').innerHTML;
const weatherIcon=c=>c===0?'☀️':c<=2?'🌤️':c===3?'☁️':c<=67?'🌧️':c<=77?'🌨️':c<=82?'🌦️':'⛈️';
function signed(v){return(Math.round(v)>0?'+':'')+Math.round(v)+'°'}
function setWeatherPlace(){const p=weatherPlaces[day];document.querySelector('#weatherLocation').textContent=p.name;document.querySelector('#weatherDate').textContent=new Date(p.date+'T12:00:00').toLocaleDateString('ru-RU',{day:'numeric',month:'long'})}
function paintWeather(data){const h=data.hourly,hours=['08:00','11:00','14:00','17:00','20:00'],rows=hours.map(t=>{const i=h.time.indexOf(weatherPlaces[day].date+'T'+t);return i<0?null:{time:t,temp:h.temperature_2m[i],feel:h.apparent_temperature[i],rain:h.precipitation_probability[i],humidity:h.relative_humidity_2m[i],wind:h.wind_speed_10m[i],code:h.weather_code[i]}}).filter(Boolean);if(!rows.length)throw new Error('Прогноз на дату пока недоступен');const n=rows[0];document.querySelector('#weatherNowLabel').textContent=n.time;document.querySelector('#weatherNowIcon').textContent=weatherIcon(n.code);document.querySelector('#weatherNowTemp').textContent=signed(n.temp);document.querySelector('#weatherFeels').textContent=signed(n.feel);document.querySelector('#weatherRain').textContent=Math.round(n.rain)+'%';document.querySelector('#weatherHumidity').textContent=Math.round(n.humidity)+'%';document.querySelector('#weatherWind').textContent=Math.round(n.wind/3.6*10)/10+' м/с';document.querySelector('#forecastList').innerHTML=rows.map(x=>`<div class="forecast-day"><span>${x.time}</span><i>${weatherIcon(x.code)}</i><b>${signed(x.temp)}</b><small>💧 ${Math.round(x.rain)}%</small></div>`).join('');document.querySelector('.forecast-list.mirror').innerHTML=document.querySelector('#forecastList').innerHTML}
async function loadWeather(force){const p=weatherPlaces[day],key=p.date+'-'+p.name,btn=document.querySelector('#refreshDayWeather'),status=document.querySelector('#weatherUpdated'),today=new Date().toISOString().slice(0,10),diff=Math.round((new Date(p.date+'T12:00:00Z')-new Date(today+'T12:00:00Z'))/86400000);if(diff<0||diff>15){status.textContent='Точный прогноз для этой даты пока недоступен — показан климатический ориентир';return}if(!force&&weatherCache[key]){paintWeather(weatherCache[key]);return}btn.classList.add('loading');status.textContent='Обновляем прогноз…';try{const q=new URLSearchParams({latitude:p.lat,longitude:p.lon,hourly:'temperature_2m,apparent_temperature,precipitation_probability,relative_humidity_2m,weather_code,wind_speed_10m',timezone:p.tz,start_date:p.date,end_date:p.date});const r=await fetch('https://api.open-meteo.com/v1/forecast?'+q);if(!r.ok)throw new Error();const data=await r.json();weatherCache[key]=data;paintWeather(data);status.textContent='Обновлено '+new Date().toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})+' · источник Open-Meteo'}catch(e){status.textContent='Актуальный прогноз на эту дату пока недоступен — показан ориентир'}finally{btn.classList.remove('loading')}}
document.querySelector('#refreshDayWeather').onclick=()=>loadWeather(true);
window.addEventListener('resize',syncCarouselHeight);window.addEventListener('load',syncCarouselHeight);
const cardHeightObserver=new ResizeObserver(syncCarouselHeight);function observeDayCards(){cardHeightObserver.disconnect();if(track)[...track.children].forEach(card=>cardHeightObserver.observe(card))}new MutationObserver(()=>setTimeout(observeDayCards,0)).observe(carousel,{childList:true,subtree:true});observeDayCards();
function inlineMd(s){return s.trim().replace(/\[([^\]]+)\]\((https?:\/\/[^)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1 ↗</a>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\n/g,'<br>')}
function parseDetailedPlan(text){return[...text.matchAll(/^## День (\d+) — (.+)\n([\s\S]*?)(?=^## День \d+ —|^## Неопределённые)/gm)].map(m=>{const title=m[2],cut=title.indexOf('. '),date=cut>-1?title.slice(0,cut):title,name=cut>-1?title.slice(cut+2):title,sections=[];for(const s of m[3].matchAll(/\*\*([^*]+)\*\*\s*([\s\S]*?)(?=\n\n\*\*|$)/g))sections.push({name:s[1].replace(/\.$/,''),html:inlineMd(s[2])});const weather=sections.find(x=>x.name==='Погода');return{date,name,sections,weather:weather?weather.html:''}})}
function renderDetailedPlan(){carousel.innerHTML='<div class="day-track">'+detailed.map((d,i)=>{const main=d.sections.filter(x=>!['Что пригодится','Погода'].includes(x.name)),tips=d.sections.find(x=>x.name==='Что пригодится');return`<article class="day-card detailed-card"><header class="day-card-head"><div><span class="date-line">${d.date}</span><h3>${d.name}</h3><b>День ${String(i+1).padStart(2,'0')}</b></div><div class="day-image" style="background-image:url(https://images.unsplash.com/photo-${images[i%images.length]}?auto=format&fit=crop&w=900&q=80)"></div></header><div class="day-columns"><section class="program"><h4>План дня</h4>${main.map(x=>`<div class="detail-section"><h5>${x.name}</h5><p>${x.html}</p></div>`).join('')}</section><aside class="day-aside"><div class="take"><h4>Взять с собой</h4>${days[i][3].split(' · ').map(x=>'<span><i>✓</i>'+x+'</span>').join('')}</div>${tips?`<div class="tip full-tip"><i>💡</i><p><b>Лайфхаки</b>${tips.html}</p></div>`:''}</aside></div></article>`}).join('')+'</div>';track=carousel.firstElementChild;showDay(day)}
fetch('plan.md?v=20260728-7').then(r=>r.text()).then(t=>{detailed=parseDetailedPlan(t);if(detailed.length===15)renderDetailedPlan()}).catch(()=>{});
const base=[['Гермопакет для телефона','weather'],['Штатив','shoot'],['Свет — 3 шт.?','shoot'],['Маленький металлический штатив','shoot'],['Сандалии','base'],['Веер','weather'],['Вентилятор на шею','weather'],['Охлаждающее колье','weather'],['Дождевик','weather'],['Полотенца','base'],['Санитайзер','base'],['Купальник','base'],['Удобные кроссовки','base'],['SPF 50','weather'],['Репеллент','weather'],['Паспорт и страховка','base'],['Личные лекарства','base']];
const legacyCustom=JSON.parse(localStorage.getItem('china-custom')||'[]'),savedItems=JSON.parse(localStorage.getItem('china-packing-items')||'null');let packingItems=savedItems||[...base.map((x,i)=>({id:'base-'+i,text:x[0],category:x[1]})),...legacyCustom.map((x,i)=>({id:'custom-old-'+i,text:x[0],category:x[1]}))],checked=JSON.parse(localStorage.getItem('china-checked')||'{}'),filter='all';
packingItems.forEach(x=>{if(Object.prototype.hasOwnProperty.call(checked,x.text)&&!Object.prototype.hasOwnProperty.call(checked,x.id))checked[x.id]=checked[x.text];delete checked[x.text]});
const packEsc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));function savePackingItems(){localStorage.setItem('china-packing-items',JSON.stringify(packingItems));localStorage.setItem('china-checked',JSON.stringify(checked))}
function renderPacking(){document.querySelector('#packingList').innerHTML=packingItems.map(x=>filter==='all'||filter===x.category?`<label class="packing-item" data-category="${x.category}"><input type="checkbox" data-id="${x.id}" ${checked[x.id]||checked[x.text]?'checked':''}><i class="checkmark"></i><span class="packing-text">${packEsc(x.text)}</span><i class="category-dot"></i><span class="item-actions"><button class="edit-item" type="button" data-id="${x.id}" aria-label="Редактировать" title="Редактировать">✎</button><button class="delete-item" type="button" data-id="${x.id}" aria-label="Удалить" title="Удалить">×</button></span></label>`:'').join('');const done=packingItems.filter(x=>checked[x.id]||checked[x.text]).length,p=Math.round(done/packingItems.length*100)||0;document.querySelector('#packingPercent').textContent=p+'%';document.querySelector('#packingProgress').style.width=p+'%';document.querySelector('#packingBadge').textContent=packingItems.length-done;document.querySelectorAll('.packing-item input').forEach(el=>el.onchange=()=>{checked[el.dataset.id]=el.checked;savePackingItems();renderPacking()});document.querySelectorAll('.edit-item').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();const item=packingItems.find(x=>x.id===b.dataset.id),value=prompt('Изменить пункт списка',item.text);if(value&&value.trim()){item.text=value.trim();savePackingItems();renderPacking()}});document.querySelectorAll('.delete-item').forEach(b=>b.onclick=e=>{e.preventDefault();e.stopPropagation();packingItems=packingItems.filter(x=>x.id!==b.dataset.id);delete checked[b.dataset.id];savePackingItems();renderPacking()})}
document.querySelectorAll('#packingFilters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#packingFilters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');filter=b.dataset.filter;renderPacking()});
document.querySelector('#addItemForm').onsubmit=e=>{e.preventDefault();const v=document.querySelector('#customItem').value.trim();if(v){packingItems.push({id:'item-'+Date.now()+'-'+Math.random().toString(16).slice(2),text:v,category:document.querySelector('#customCategory').value});savePackingItems();e.target.reset();renderPacking()}};savePackingItems();renderPacking();
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab,.view').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.view+'View').classList.add('active')});
document.querySelector('#refreshWeather').onclick=e=>{e.currentTarget.classList.add('spin');setTimeout(()=>e.currentTarget.classList.remove('spin'),900)};
